name: Nodalia Video Core
version: 0.3.2
slug: nodalia_video_core
description: Stable local video bridge for Home Assistant cameras
url: https://github.com/danielmigueltejedor/apps-nodalia
startup: services
init: false
host_network: true
panel_icon: mdi:cctv
ingress: true
ingress_port: 8099
ingress_stream: true
panel_title: Nodalia Video Core
arch:
  - aarch64
  - amd64
ports:
  8099/tcp: 8099
  1984/tcp: 1984
  8554/tcp: 8554
  8555/tcp: 8555
map:
  - config:rw
  - share:rw
options:
  log_level: info
  cameras: ""
schema:
  log_level: list(debug|info|warning|error)
  cameras: str?
