name: Codacy Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Codacy ShellCheck
        uses: codacy/codacy-analysis-cli-action@d840f886c4bd4edc059706d09c6a1586111c540b
        with:
          verbose: true
          format: sarif
          output: results.sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          tool: shellcheck

      - name: Upload SARIF to GitHub code scanning
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
